name: SMS Bomber Worker

on:
  workflow_dispatch:
    inputs:
      phone:
        description: 'Target phone number'
        required: true
      chat_id:
        description: 'Telegram chat ID'
        required: true
      user_id:
        description: 'Telegram user ID'
        required: true

jobs:
  bomber:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp aiohttp_socks python-telegram-bot pytz
          
      - name: Run bomber
        env:
          PHONE: ${{ github.event.inputs.phone }}
          CHAT_ID: ${{ github.event.inputs.chat_id }}
        run: |
          python src/worker.py
